---
title: "Prepare for Bayesian Dynamic Borrowing"
subtitle: "Last updated `r Sys.Date()`"
author: "Artemis Koukounari, Matt Secrest (alphabetical)"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    keep_md: FALSE
---

```{r setup,include = FALSE}
knitr::opts_chunk$set(eval = TRUE,         # Evaluate code
                      echo = FALSE,         # echo code?
                      message = FALSE,     # Show messages
                      warning = FALSE,     # Show warnings
                      fig.width = 12,       # Default plot width
                      fig.height = 8,      # .... height
                      dpi = 300,           # Plot resolution
                      fig.align = "left")  # Figure alignment 
```


# Confirm parametric modeling results in JAGS{.tabset .tabset-pills .tabset-fade}

## MORPHEUS-Only{.tabset .tabset-pills .tabset-fade}

### Weibull

```{r}
summary(bdb_prep_model_1_A_cs)
```


### Exponential

```{r}
summary(bdb_prep_model_2_A_cs)
```

## Flatiron atezo 1:1 PS matched to MORPHEUS atezo{.tabset .tabset-pills .tabset-fade}

### Weibull

```{r}
summary(bdb_prep_model_1_B_cs)
```


### Exponential

```{r}
summary(bdb_prep_model_2_B_cs)
```


## Flatiron atezo meeting inclusion criteria{.tabset .tabset-pills .tabset-fade}

### Weibull

```{r}
summary(bdb_prep_model_1_C_cs)
```


### Exponential

```{r}
summary(bdb_prep_model_2_C_cs)
```
